# Generated by Django 4.1.6 on 2023-02-17 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_userprofile_bio_userprofile_is_prenium'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_prenium',
            new_name='is_premium',
        ),
    ]
